# DOT_DEST=.config/starship.toml

format = """
[in ](blue)$directory$git_branch$git_commit$git_state$git_status$python$cmd_duration
 $character"""

[cmd_duration]
min_time = 500
format = "[took ](cyan)[$duration](bold cyan)"

[python]
format = 'via [Python ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
