#!/bin/bash
# DOT_DEST=.xinitrc
# xrandr --setprovideroutputsource NVIDIA-0 modesetting
# xrandr --auto
xrdb -load ~/.Xresources
~/dotty2hotty/scripterino/utils/wall.sh
# unclutter & # moved to i3_services
xset -b # turn off beeping
setxkbmap -option ctrl:nocaps
exec dbus-run-session i3
