#!/bin/bash
# DOT_DEST=.xinitrc
xrdb -load ~/.Xresources
~/dotty2hotty/scripterino/utils/wall.sh
unclutter &
redshift &
xset -b # turn off beeping
[ -f ~/dotty2hotty/config_files/xmodmaprc_logitech ] && xmodmap ~/dotty2hotty/config_files/xmodmaprc_logitech
exec dbus-run-session i3
