#
# DOT_DEST=.zprofile
#

# Environment variables
export EDITOR=vim
export SVDIR=${HOME}/.local/var/service
export GPODDER_HOME=${HOME}/.config/gPodder
export GPODDER_DOWNLOAD_DIR=${HOME}/dumbshit/podcasts
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
export QT_QPA_PLATFORMTHEME=qt5ct
export DOOMDIR=${HOME}/.config/doom.d

if [[ -z $TMUX ]] && [[ -z $SSH_CLIENT ]] && [[ -z $SSH2_CLIENT ]] && [[ "$TTY" = "/dev/tty1" ]]; then
  startx
fi
