#!/usr/bin/env bash

_help () {
  echo \
"USAGE: musicsync [-p PORT] [-d] [-r] [<target_ip>]
    -p PORT      assign target port number
    -d           delete files missing from host
    -r           switch host and target (reverse)
    -h HOSTNAME  fetch host info from ssh_config"
}

rsync_delete_flag=""
reverse=""

target_ip=192.168.0.179
target_port=22

target_hostname="ph1"

while getopts "drp:h:" opt
do
  case ${opt} in
    p)
      target_port=${OPTARG}
      ;;
    r)
      reverse="-r"
      ;;
    d)
      rsync_delete_flag="--delete"
      ;;
    h)
      target_hostname=${OPTARG}
      ;;
    *)
      _help
      exit 1
  esac
done

ssh_G_output=$( ssh -G "${target_hostname}" 2> /dev/null )
target_ip=$( echo "$ssh_G_output" | grep "^hostname " | awk '{ print $2 }' )
target_port=$( echo "$ssh_G_output" | grep "^port " | awk '{ print $2 }' )

shift $((OPTIND - 1))
if [ -n "$*" ]
then
  target_ip="$*"
fi

host_music_dir=~/Music/synced_music
target_music_dir=/sdcard/Music/synced_music

echo "Syncing files:"

if [ -z "${reverse}" ]
then
  src=${host_music_dir%/}/
  dest=${target_ip}:${target_music_dir%/}/
  echo "Source : ${src}"
  echo "Dest.  : ${dest}, Port ${target_port}"
else
  src=${target_ip}:/sdcard/Music/synced_music/
  dest=~/Music/synced_music/
  echo "Source : ${src}, Port ${target_port}"
  echo "Dest.  : ${dest}"
fi

rsync --recursive --size-only --verbose --progress --ignore-existing\
  -e "ssh -p ${target_port}" ${rsync_delete_flag}\
  "${src}" "${dest}"
