#!/bin/bash

if [ ! -x /usr/bin/cmus-remote ];
then
  echo "cmus is not installed."
  exit
fi

ARTIST=$( cmus-remote -Q 2>/dev/null | grep "tag artist" | cut -d " " -f 3- )
TITLE=$( cmus-remote -Q 2>/dev/null | grep "tag title" | cut -d " " -f 3- )
FILENAME=$( cmus-remote -Q 2>/dev/null | grep "file " | cut -d " " -f 2- )

# Generate output string
if [ -n "$TITLE" ];
then
  OUTPUT="\"$TITLE\" by $ARTIST"
elif ] -n "$FILENAME" ];
then
  OUTPUT="$FILENAME"
else
  OUTPUT=""
fi

# Splice output if it is too long
if [ ${#OUTPUT} -ge 28 ]
then
  OUTPUT="$( echo $OUTPUT | cut -c -25 )..."
fi

# Echo the crap of out it
echo $OUTPUT
