#!/bin/bash

if [ ! -x /usr/bin/cmus-remote ];
then
  echo "cmus is not installed."
  exit
fi

ARTIST=$( cmus-remote -Q 2>/dev/null | grep "tag artist" | cut -d " " -f 3- )
TITLE=$( cmus-remote -Q 2>/dev/null | grep "tag title" | cut -d " " -f 3- )
FILENAME=$( cmus-remote -Q 2>/dev/null | grep "file" | cut -d " " -f 2- )

if [ -n "$TITLE" ];
then
   notify-send "\"$TITLE\"" "by $ARTIST"
elif [ -n "$FILENAME" ];
then
   notify-send "${FILENAME##*/}"
fi
