#!/bin/bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

OPTIONS="reboot\nshutdown\nsuspend\nhibernate\nkill-i3"

# source configuration or use default values
LAUNCHER="rofi -dmenu -lines 5 -width 25 -p adieu:"
USE_LOCKER="false"
LOCKER="i3lock"

# Show exit wm option if exit command is provided as an argument
# if [ ${#1} -gt 0 ]; then
#   OPTIONS="kill-i3\n$OPTIONS"
# fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      kill-i3)
        i3-msg exit
        ;;
      reboot)
        systemctl reboot
        ;;
      shutdown)
        systemctl poweroff
        ;;
      suspend)
        systemctl suspend
        ;;
      hibernate)
        systemctl hibernate
        ;;
      *)
        ;;
    esac
fi
