#!/bin/bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

OPTIONS="1. hibernate\n2. reboot\n3. shutdown\n4. suspend\n5. kill-i3"

# source configuration or use default values
LAUNCHER="rofi -dmenu -lines 5 -width 25 -p adios:"
USE_LOCKER="false"
LOCKER="i3lock"

# Show exit wm option if exit command is provided as an argument
# if [ ${#1} -gt 0 ]; then
#   OPTIONS="kill-i3\n$OPTIONS"
# fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      1. hibernate)
        systemctl hibernate
        ;;
      2. reboot)
        systemctl reboot
        ;;
      3. shutdown)
        systemctl poweroff
        ;;
      4. suspend)
        systemctl suspend
        ;;
      5. kill-wm)
        i3-msg exit
        ;;
      *)
        ;;
    esac
fi
