#!/usr/bin/env sh

# battery number under acpi
BATTERY=0

capacity=$(acpi -b | grep "Battery ${BATTERY}:" | cut -d':' -f2 | cut -d',' -f2 | cut -c2-)
status=$(acpi -b | grep "Battery ${BATTERY}:" | cut -d':' -f2 | cut -d',' -f1)

if [ "$status" = " Charging" ]; then
  symbol="+"
elif [ "$status" = " Discharging" ]; then
  symbol="-"
else
  symbol="="
fi

echo "$capacity $symbol "
