#!/bin/env sh

maxlen=40

# Check if mpc/mpd is installed
! command -v mpc 1> /dev/null && echo "mpc is not installed." && exit

format_string='[["%title%"][ by %artist%]]|[%file%]'

# Store mpc output
set -f
IFS='
'
set -- $(mpc -f "${format_string}")
set +f

# Exit if mpd is not running
if [ -z "$1" ]
then
  echo "mpd down"
  exit
fi

# Exit if queue is empty
if [ -z "$2" ]
then
  echo "mpd queue empty"
  exit
fi

# Check if ashuffle is running
if pgrep -x ashuffle > /dev/null 2>&1
then
  ashuffle=" <ash>"
fi
 
# Splice output if it is too long
if [ ${#1} -ge ${maxlen} ]
then
  song_info="$( printf "%.${maxlen}s…" "$1" )"
else
  song_info="$1"
fi

# Show `|` if paused, `>` if playing
if [ "${2%]*}" = "[playing" ]
then
  symbol=">"
else
  symbol="|"
fi

# Get mpd's volume
vol="${3#*:}"
vol="${vol%\%*}"
vol="${vol# }"

# Echo the crap of out it
if [ -n "$song_info" ]
then
  echo "${symbol} ${song_info} <${vol}%>${ashuffle}"
fi
